//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Orm
{
    using System;
    
    public enum Sex : int
    {
        Mail = 0,
        Femail = 1,
        Third = 2
    }
}
